### PR TITLE
Show summary

### LINKED ISSUE #11: Post suite summaries
After completing a suite, a summary of some kind would be nice:
```
testlogger {
    showSummary true|false
}
```

The color in the current output is extremely useful for finding exactly which test failed while scrolling through, the summary could be an at-a-glance way to know what failed. I'm thinking the following pieces of information would be useful:

- Task status: SUCCESSFUL/FAILED/ERROR
- Number of tests
- Number passed
- Number skipped
- Number failed
- Number errored
- List of Package/Class/Method of failed and errored tests

I've been putting the following in our build.gradle files, but it would be nice not to have to repeat it everywhere:
```
afterSuite { desc, result ->
       if (!desc.parent) { // will match the outermost suite
           def output = "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} successes, ${result.failedTestCount} failures, ${result.skippedTestCount} skipped)"
           def startItem = '|  ', endItem = '  |'
           def repeatLength = startItem.length() + output.length() + endItem.length()
           println('\n' + ('-' * repeatLength) + '\n' + startItem + output + endItem + '\n' + ('-' * repeatLength))
       }
   }
```

### PR DESCRIPTION
**Pull request by radarsh**
Fixes #11 and #35

### CODE REVIEW

File: src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy [hunk 1]
```diff
@@ -10,23 +11,30 @@ import static org.gradle.api.logging.configuration.ConsoleOutput.Plain
...
+
+    private final ConsoleOutput consoleType
 
     TestLoggerExtension(Project project) {
+        this.consoleType = project.gradle.startParameter.consoleOutput
         this.theme = project.gradle.startParameter.consoleOutput == Plain ? PLAIN : this.theme
     }
 
     void setTheme(String theme) {
+        if (consoleType == Plain) {
```
Comment (ataverasp) [inline src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy]: for me this is failing when we have parallel test enabled. I think that in line 22 we can check if maxParallelForks is greater than 1 and use Plain Parallel instead

Comment (radarsh) [reply src/main/groovy/com/adarshr/gradle/testlogger/TestLoggerExtension.groovy]: Yeah. I am inclined to agree now. We should make it a bit more generic and always switch to a parallel theme. Let me think about this again. It also echoes [cjstehno's](#88) thoughts.
